logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.wmachaca.airbnbclone: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-clone-back
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: airbnb_clone
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8089

okta:
  oauth2:
    issuer: https://airbnb-clon.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_DXRlpxifp9FLxZKz
